version: 2.1

orbs:
  hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image

workflows:
  "Hello Workflow":
    jobs:
      parallelism: 2
        working_directory: /everydayrails-rspec-2017withCircleci
      steps:
        - run:
            name: run tests
            command: |
              rails test test
