version: 2.1

workflows:
  "Hello Workflow":
    jobs:
        build:
          docker:
            - image: circleci/ruby:2.5.0
        test:
          docker:
            - image: circleci/ruby:2.5.0
        parallelism: 2
        working_directory: ~/everydayrails-rspec-2017withCircleci
          steps:
            - run:
              name: Bundle Install
              command: bundle check || bundle install
            - run:
                name: RSpec
                command: |
                  circleci tests glob \
                  spec/controllers/**/*.rb \
                  spec/models/**/*.rb \
                  spec/features/**/*.rb \
                  spec/requests/**/*.rb \
                  xargs bundle exec rspec
